apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trips
        image: registryuxy0369.azurecr.io/openhack-trips:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: trips-db-user-pass
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trips-db-user-pass
              key: password      
        #- name: SQL_PASSWORD
        #  value: "_YourStrong@Passw0rd"
        #- name: SQL_USER
        #  value: "sqladminuXy0369"  
        - name: SQL_SERVER
          value: "sqlserveruxy0369.database.windows.net"
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"

---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  ports:
  - port: 80
  selector:
    app: trips
