apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registryuxy0369.azurecr.io/openhack-user-java:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 1024Mi
        ports:
        - containerPort: 80
        env:
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: PORT
          value: "80"
        volumeMounts:
          - name: sql-credentials
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: sql-credentials
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "humo-kv-class"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: user-java          
